name: Python Style Check

on: [push, pull_request]

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Check Style
        run: |
            black --check dico
            isort -c --profile=black dico